create table if not exists public.run (
  id bigint generated by default as identity primary key,
  created_at timestamp without time zone not null default timezone('utc'::text, now()),
  filename text not null,
  predicted_class text not null,
  confidence double precision not null,
  probabilities text not null,
  preview_b64 text not null,
  rca_json text
);

create index if not exists ix_run_created_at
  on public.run (created_at);

create index if not exists ix_run_predicted_class
  on public.run (predicted_class);
